### ISSUE TITLE
Error: CppCheck executable not found ()

### ISSUE THREAD

**Issue by chenyulue** [michelou/llvm-examples#1]
When I ran `.\setenv` in pwsh, I got the error `Error: CppCheck executable not found ()`. Does it mean that I have to install the C++ development toolkit in VS 2019?

BTW, is it necessary to set up the same directory as yours? In my computer, I installed `cmake` by msys2, and llvm binary, python and git are installed in a different location, but all the executables are set in the `PATH` environment.  Is my setup OK for running `build.bat`?

Thanks!

**Comment by michelou** [comment]
@chenyulue Thanks for your feedback !

I just checked my environment; you're correct, I need to update my [`READ.md`](https://github.com/michelou/llvm-examples/blob/master/README.md) file to mention the requirements for [CppCheck](http://cppcheck.sourceforge.net/) (similarly to [Doxygen](https://www.doxygen.nl/download.html)).

[CppCheck](http://cppcheck.sourceforge.net/) has its own installation. From lines 245-250 in batch file [`setenv.bat`](https://github.com/michelou/llvm-examples/blob/238c1bf12e8758dea5276fb005231f12a9445ea9/setenv.bat#L245) we see that the [CppCheck](http://cppcheck.sourceforge.net/) installation is searched for in two locations :
- either in directory `%ProgramFiles%`
- or in directory `C:\opt\`

I thus invite you to install [CppCheck](http://cppcheck.sourceforge.net/) in one of those locations; let me know if you still have issues.

On my side I will improve the `.md`/`.bat` files regarding the usage of [CppCheck](http://cppcheck.sourceforge.net/).

**Comment by chenyulue** [comment]
well, I have installed cppcheck my msys2, and made a symbolic link to it in the opt directory. Now I have a new problem related to the MS SDK 7.1, saying cann't find the installation directory. 

My os is win10, and MS sdk 7.1 needs .netframework 4. I am still working on how to install sdk 7.1.

**Comment by michelou** [comment]
@chenyulue Note that most of the complexity of the project settings comes from my attempt to provide support for several toolsets (e.g. MSVC/MSBuild, Clang/GNU Make and GCC/GNU Make) to build the [LLVM examples](https://github.com/michelou/llvm-examples/blob/master/examples/README.md).

**Comment by chenyulue** [comment]
Then Sdk 7.1 is needed to support MSVC, right? If I only use the GCC/GNU Make toolset,  can I delete the snippet related to the SDK 7.1? If possible, how? 

Thanks!

**Comment by michelou** [comment]
@chenyulue Correct. The pair MSVC + SDK 7.1 is mandatory only to build the LLVM tools not included in the LLVM software distribution (e.g. [`LLVM-11.0.1-win64.exe`](https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.1)).

Commands like [`clang.exe`](https://releases.llvm.org/11.0.0/tools/clang/docs/ClangCommandLineReference.html), [`lld.exe`](https://lld.llvm.org/) and [`lldb.exe`](https://lldb.llvm.org/) belong to the original distribution while commands like [`llc.exe`](https://llvm.org/docs/CommandGuide/llc.html), [`lli.exe`](https://llvm.org/docs/CommandGuide/lli.html) and [`opt.exe`](https://llvm.org/docs/CommandGuide/opt.html) are build/added from the LLVM source distribution (see also file [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md)).

**Comment by chenyulue** [comment]
After installing sdk v7.1, I run `.\setenv -llvm:9 -verbose`, and get the following information:

```shell
Warning: lli executable not found in directory "C:\opt\LLVM\"
(LLVM installation directory needs additional binaries)
Tool versions:
   clang 9.0.0, doxygen 1.9.1, pelook v1.70,
   make 4.3, gcc 10.2.0,
   git 2.30.0.windows.1, vswhere 2.7.1+180c706d56
Tool paths:
INFO: Could not find "C:\msys64\mingw64\bin\\bin:cmake.exe".
INFO: Could not find "C:\\bin:bash.exe".
   C:\opt\LLVM\bin\clang.exe
   C:\opt\doxygen-1.9.1\bin\doxygen.exe
   L:\bin\pelook.exe
   C:\msys64\usr\bin\make.exe
   C:\msys64\mingw64\bin\gcc.exe
   C:\Program Files\Git\cmd\git.exe
   L:\bin\vswhere.exe
Environment variables:
   CMAKE_HOME="C:\msys64\mingw64\bin\"
   CPPCHECK_HOME="C:\msys64\mingw64\bin\"
   DOXYGEN_HOME="C:\opt\doxygen-1.9.1"
   LLVM_HOME="C:\opt\LLVM\"
   MSVC_HOME="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC"
   MSVS_HOME="C:\Program Files (x86)\Microsoft Visual Studio\2019"
   MSVS_CMAKE_HOME="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\"
   MSYS_HOME="C:\msys64\usr\"
   PYTHON_HOME="C:\msys64\mingw64\bin\"
```

I don't know whether the environment is set up correctly. Since all the tools are in my `PATH`, I try to run `.\build -verbose compile` in the `L:\llvm-9.0.0.src` directory, but get the following error:

```shell
ERROR: Value for '/r' option cannot be empty.
Type "WHERE /?" for usage.
Error: Internal error (vcvarsall.bat not found)
( was unexpected at this time.
```
 It seems that something goes wrong related to my VS 2019 installation. I actually installed the C++ toolsets, as follows:
![2021-01-25_181029](https://user-images.githubusercontent.com/44137770/105691893-c1d98f00-5f38-11eb-87b6-4756430ba364.jpg)

**Comment by michelou** [comment]
@chenyulue From file [`README.md`](https://github.com/michelou/llvm-examples/blob/master/README.md) I read :
```
Environment variables:
   CMAKE_HOME="C:\opt\cmake-3.19.2-win64-x64"
   CPPCHECK_HOME="C:\Program Files\Cppcheck"
   DOXYGEN_HOME="C:\opt\doxygen-1.9.1"
   LLVM_HOME="C:\opt\LLVM-11.0.1"
   MSVC_HOME="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC"
   MSVS_HOME="C:\Program Files (x86)\Microsoft Visual Studio\2019"
   MSVS_CMAKE_HOME="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\..\Cmake"
   MSYS_HOME="C:\opt\msys64"
   PYTHON_HOME="C:\opt\Python-3.9.1"
```
The general rule is : a `<tool>_HOME` environment variable points to the installation directory of the tool, *not* to the `bin/` directory containing the executable(s).

I still have to update file [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md); I will also run again `L:\llvm-11.0.1.src\build.bat` (in my case additional executables/libraries are already installed in `C:\opt\LLVM-11.0.1\`) to confirm that it executes successfully.

**Comment by michelou** [comment]
@chenyulue I'm done.
- Markdown files are up-to-date.
- Execution of [`build.bat`](https://github.com/michelou/llvm-examples/blob/master/bin/llvm/build.bat) in directory `L:\llvm-11.0.1.src\` is successful.

```
L:\llvm-11.0.1.src$ build -timer -verbose clean compile
Delete directory "build"
Toolset: MSVC/MSBuild, Project: LLVM
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.2
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt"
LIB="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64;"
Configuration: Release, Platform: x64
Generate configuration files into directory "build"
-- Version: 0.0.0
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
CMake Warning at utils/benchmark/CMakeLists.txt:244 (message):
  Using std::regex with exceptions disabled is not fully supported


-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_EXECUTABLE


Generate LLVM executables (LLVM.sln)
Total elapsed time: 01:14:38

L:\llvm-11.0.1.src$ dir build\Release\bin\ll?.exe | findstr /b [0-9]
25.01.2021  16:30        52 828 160 llc.exe
25.01.2021  16:30        19 796 992 lli.exe
```

**Comment by chenyulue** [comment]
Thanks! I'll try it again.

**Comment by michelou** [comment]
No feedback for over six months.
