### ISSUE TITLE
I am so interesting in your project,please tell me how to build your project on windows!

### ISSUE THREAD

**Issue by harrisonGPU** [michelou/llvm-examples#2]
I have built LLVM on my computer,the commands is :cmake -G "Visual Studio 16 2019" ../llvm in my llvm-project/build,and then :cmake --build .  --target install,and then I git clone your project,and than I create build folder, and then run cmake commands

**Comment by michelou** [comment]
@TSWorld1314 Did you have a look at the document [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md) ?

**Comment by harrisonGPU** [comment]
> @TSWorld1314 Did you have a look at the document [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md) ?

Thanks reply！I am going to look at！！！

**Comment by harrisonGPU** [comment]
> @TSWorld1314 Did you have a look at the document [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md) ?

I copy the build.bat in my llvm.src,and run command:`PS D:\llvm-project-14.0.6.src> .\build -verbose compile`,it will be error: `Error: Internal error (vcvarsall.bat not found) ` ,

**Comment by harrisonGPU** [comment]
> @TSWorld1314 Did you have a look at the document [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md) ?

like this commands:
`PS D:\llvm-project\llvm> .\build help`
`error: options '/r' cannot be empty.`
`input "WHERE /?" for usage`
`Error: Internal error (vcvarsall.bat not found)`
`At this time there should be no (`

**Comment by harrisonGPU** [comment]
Please tell me how do to it,I reall want to learn this project!

**Comment by michelou** [comment]
At this point I suggest you to follow the 2 steps below to make progress with your local LLVM build.
- You create a local copy (using `git clone`) of my `llvm-examples` repository.
- You read **VERY** carefully (and in order) the 2 pages [`README.md`](https://github.com/michelou/llvm-examples/blob/master/README.md) and [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md) to get the same environment as mine before trying to generate a local LLVM build (I started with LLVM 8.0 a long time ago and I now use LLVM 14.0.6).
   **NB.** The batch file `build.bat` I wrote to generate the LLVM build needs both the tools *and* the environment variables to be corrected  installed resp. defined.

**Comment by harrisonGPU** [comment]
> At this point I suggest you to follow the 2 steps below to make progress with your local LLVM build.
> 
> * You create a local copy (using `git clone`) of my `llvm-examples` repository.
> * You read **VERY** carefully (and in order) the 2 pages [`README.md`](https://github.com/michelou/llvm-examples/blob/master/README.md) and [`BUILD.md`](https://github.com/michelou/llvm-examples/blob/master/BUILD.md) to get the same environment as mine before trying to generate a local LLVM build (I started with LLVM 8.0 a long time ago and I now use LLVM 14.0.6).
>   **NB.** The batch file `build.bat` I wrote to generate the LLVM build needs both the tools _and_ the environment variables to be corrected  installed resp. defined.

Thanks a lot.I try to do it!I really appreciate！
